-- Add realistic Ghana property listings based on market research
-- Properties from various locations: Accra, Kumasi, East Legon, Airport Residential, etc.

INSERT INTO properties (
  title, 
  description, 
  location, 
  price, 
  bedrooms, 
  bathrooms, 
  property_type, 
  listing_type, 
  area, 
  parking,
  amenities, 
  images, 
  agent, 
  phone, 
  status, 
  featured
) VALUES 
(
  'Luxury 3 Bedroom Apartment in Airport Residential',
  'Stunning modern apartment in the heart of Airport Residential. This beautifully designed 3-bedroom unit features contemporary finishes, spacious living areas, and breathtaking city views. Perfect for executives and families seeking comfort and convenience in one of Accra''s most prestigious neighborhoods.',
  'Airport Residential, Accra',
  450000,
  3,
  3,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale' to match database constraint
  180,
  2,
  ARRAY['Swimming Pool', '24/7 Security', 'Gym/Fitness Center', 'Backup Generator', 'Air Conditioning', 'Balcony/Terrace', 'CCTV Surveillance', 'Internet/WiFi', 'Elevator'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Accential Properties',
  '+233 50 123 4567',
  'active',
  true
),
(
  '4 Bedroom Detached House in East Legon',
  'Magnificent 4-bedroom detached house in the exclusive East Legon area. This property boasts elegant architecture, spacious rooms, a beautiful garden, and modern amenities. Ideal for families looking for luxury living in a secure, gated community.',
  'East Legon, Accra',
  850000,
  4,
  5,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  350,
  4,
  ARRAY['Swimming Pool', '24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Air Conditioning', 'Servant Quarters', 'CCTV Surveillance', 'Water Storage/Tank', 'Gated Community', 'Solar Panels'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Noah Claypole Properties',
  '+233 24 567 8901',
  'active',
  true
),
(
  '2 Bedroom Apartment in Cantonments',
  'Charming 2-bedroom apartment in the prestigious Cantonments area. Features include modern fittings, ample natural light, and proximity to embassies, restaurants, and shopping centers. Perfect for young professionals and small families.',
  'Cantonments, Accra',
  320000,
  2,
  2,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale'
  120,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Parking', 'Air Conditioning', 'Balcony/Terrace', 'CCTV Surveillance', 'Internet/WiFi'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Shelter Mart Gh Ltd',
  '+233 20 345 6789',
  'active',
  false
),
(
  '5 Bedroom Villa in Ridge',
  'Exquisite 5-bedroom villa in the heart of Ridge. This stunning property features high ceilings, marble floors, a private pool, and lush gardens. Located in one of Accra''s most sought-after neighborhoods, close to government offices and international schools.',
  'Ridge, Accra',
  1200000,
  5,
  6,
  'Villa',
  'sale', -- Changed from 'For Sale' to 'sale'
  500,
  5,
  ARRAY['Swimming Pool', '24/7 Security', 'Gym/Fitness Center', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Air Conditioning', 'Servant Quarters', 'CCTV Surveillance', 'Water Storage/Tank', 'Gated Community', 'Internet/WiFi', 'Solar Panels'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Realtor & Tours',
  '+233 55 789 0123',
  'active',
  true
),
(
  '3 Bedroom Townhouse in Aburi',
  'Beautiful 3-bedroom townhouse in the serene hills of Aburi. Enjoy cool weather, fresh air, and stunning mountain views. This property features modern design, spacious rooms, and a private garden. Perfect for those seeking tranquility away from the city.',
  'Aburi, Eastern Region',
  380000,
  3,
  4,
  'Townhouse',
  'sale', -- Changed from 'For Sale' to 'sale'
  200,
  3,
  ARRAY['24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Balcony/Terrace', 'CCTV Surveillance', 'Water Storage/Tank', 'Gated Community'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Gabriel Ametorwoshie',
  '+233 24 111 2222',
  'active',
  false
),
(
  '4 Bedroom House in Kumasi Metropolitan',
  'Spacious 4-bedroom house in Kumasi Metropolitan area. This well-maintained property offers comfortable living spaces, a large compound, and easy access to schools, markets, and major roads. Great value for families.',
  'Kumasi Metropolitan, Ashanti',
  420000,
  4,
  3,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  280,
  3,
  ARRAY['24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Water Storage/Tank', 'Gated Community'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Wonder Ahorku',
  '+233 32 456 7890',
  'active',
  false
),
(
  '1 Bedroom Studio Apartment in Osu',
  'Modern 1-bedroom studio apartment in vibrant Osu. Perfect for young professionals, this unit features an open-plan design, modern kitchen, and is within walking distance to Oxford Street, beaches, restaurants, and nightlife.',
  'Osu, Accra',
  180000,
  1,
  1,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale'
  65,
  1,
  ARRAY['24/7 Security', 'Backup Generator', 'Air Conditioning', 'Internet/WiFi', 'Elevator'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Accential Properties',
  '+233 50 123 4567',
  'active',
  false
),
(
  '3 Bedroom Apartment for Rent in Labone',
  'Fully furnished 3-bedroom apartment available for rent in Labone. This property includes modern appliances, air conditioning in all rooms, and 24/7 security. Close to embassies, international schools, and shopping centers.',
  'Labone, Accra',
  3500,
  3,
  2,
  'Apartment',
  'rent', -- Changed from 'For Rent' to 'rent'
  150,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Parking', 'Air Conditioning', 'CCTV Surveillance', 'Internet/WiFi'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Shelter Mart Gh Ltd',
  '+233 20 345 6789',
  'active',
  false
),
(
  '2 Bedroom House in Kasoa',
  'Affordable 2-bedroom house in Kasoa. This property offers great value for first-time buyers or investors. Features include a spacious compound, modern bathroom, and easy access to the main road and public transport.',
  'Kasoa, Central Region',
  150000,
  2,
  2,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  100,
  2,
  ARRAY['Parking', 'Water Storage/Tank'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Gabriel Ametorwoshie',
  '+233 24 111 2222',
  'active',
  false
),
(
  '4 Bedroom Apartment in Trasacco Valley',
  'Luxurious 4-bedroom apartment in the exclusive Trasacco Valley Estate. This premium property features top-of-the-line finishes, smart home technology, and access to world-class estate amenities including golf course, tennis courts, and clubhouse.',
  'Trasacco Valley, East Legon',
  950000,
  4,
  4,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale'
  280,
  3,
  ARRAY['Swimming Pool', '24/7 Security', 'Gym/Fitness Center', 'Backup Generator', 'Parking', 'Air Conditioning', 'CCTV Surveillance', 'Gated Community', 'Internet/WiFi', 'Solar Panels', 'Clubhouse Access'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Noah Claypole Properties',
  '+233 24 567 8901',
  'active',
  true
),
(
  '3 Bedroom House in Adenta',
  'Well-designed 3-bedroom house in Adenta. This property features modern architecture, spacious rooms, and a beautiful garden. Located in a peaceful neighborhood with good road access and close to schools and shopping centers.',
  'Adenta, Accra',
  280000,
  3,
  3,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  180,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Water Storage/Tank'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Wonder Ahorku',
  '+233 32 456 7890',
  'active',
  false
),
(
  '5 Bedroom Executive House in Spintex',
  'Executive 5-bedroom house in Spintex Road area. This impressive property features a swimming pool, spacious living areas, modern kitchen, and servant quarters. Perfect for large families or executives seeking comfort and style.',
  'Spintex, Accra',
  720000,
  5,
  5,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  400,
  4,
  ARRAY['Swimming Pool', '24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Air Conditioning', 'Servant Quarters', 'CCTV Surveillance', 'Water Storage/Tank', 'Internet/WiFi'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Realtor & Tours',
  '+233 55 789 0123',
  'active',
  false
),
(
  '2 Bedroom Apartment for Rent in Tema',
  'Comfortable 2-bedroom apartment for rent in Tema Community 25. This unit features modern amenities, is close to the harbor, and offers easy access to Accra. Ideal for professionals working in Tema or the Free Zones.',
  'Tema, Greater Accra',
  2800,
  2,
  2,
  'Apartment',
  'rent', -- Changed from 'For Rent' to 'rent'
  110,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Parking', 'Water Storage/Tank'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Accential Properties',
  '+233 50 123 4567',
  'active',
  false
),
(
  '4 Bedroom House in Oyarifa',
  'Spacious 4-bedroom house in the rapidly developing Oyarifa area. This property offers great value with modern design, ample parking, and a large compound. Perfect for families looking for affordable housing in a growing community.',
  'Oyarifa, Accra',
  350000,
  4,
  3,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  250,
  3,
  ARRAY['24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Water Storage/Tank', 'Gated Community'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Shelter Mart Gh Ltd',
  '+233 20 345 6789',
  'active',
  false
),
(
  '3 Bedroom Apartment in Dzorwulu',
  'Modern 3-bedroom apartment in Dzorwulu. This well-maintained property features contemporary design, spacious bedrooms, and is located in a quiet neighborhood close to embassies and international organizations.',
  'Dzorwulu, Accra',
  420000,
  3,
  3,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale'
  160,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Parking', 'Air Conditioning', 'Balcony/Terrace', 'CCTV Surveillance', 'Internet/WiFi', 'Elevator'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Gabriel Ametorwoshie',
  '+233 24 111 2222',
  'active',
  false
),
(
  '6 Bedroom Mansion in Roman Ridge',
  'Spectacular 6-bedroom mansion in the prestigious Roman Ridge area. This architectural masterpiece features luxury finishes throughout, a home theater, wine cellar, infinity pool, and panoramic city views. The ultimate in luxury living.',
  'Roman Ridge, Accra',
  2500000,
  6,
  7,
  'Mansion',
  'sale', -- Changed from 'For Sale' to 'sale'
  800,
  6,
  ARRAY['Swimming Pool', '24/7 Security', 'Gym/Fitness Center', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Air Conditioning', 'Servant Quarters', 'CCTV Surveillance', 'Water Storage/Tank', 'Gated Community', 'Internet/WiFi', 'Solar Panels', 'Home Theater'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Noah Claypole Properties',
  '+233 24 567 8901',
  'active',
  true
),
(
  '3 Bedroom House in Weija',
  'Lovely 3-bedroom house in Weija. This property offers comfortable living with modern amenities, a nice garden, and is located in a peaceful residential area. Good access to the Accra-Winneba road and close to schools.',
  'Weija, Accra',
  320000,
  3,
  3,
  'House',
  'sale', -- Changed from 'For Sale' to 'sale'
  190,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Water Storage/Tank'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Wonder Ahorku',
  '+233 32 456 7890',
  'active',
  false
),
(
  '2 Bedroom Apartment in Dansoman',
  'Affordable 2-bedroom apartment in Dansoman. This property is perfect for first-time buyers or investors. Features include modern fittings, good ventilation, and proximity to the beach, markets, and transport links.',
  'Dansoman, Accra',
  195000,
  2,
  2,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale'
  95,
  1,
  ARRAY['24/7 Security', 'Parking', 'Water Storage/Tank'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Realtor & Tours',
  '+233 55 789 0123',
  'active',
  false
),
(
  '4 Bedroom House for Rent in Achimota',
  'Spacious 4-bedroom house available for rent in Achimota. This property features a large living area, modern kitchen, ample parking, and a beautiful garden. Close to Achimota Mall, schools, and the motorway.',
  'Achimota, Accra',
  4500,
  4,
  3,
  'House',
  'rent', -- Changed from 'For Rent' to 'rent'
  220,
  3,
  ARRAY['24/7 Security', 'Backup Generator', 'Garden/Lawn', 'Parking', 'Water Storage/Tank'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Shelter Mart Gh Ltd',
  '+233 20 345 6789',
  'active',
  false
),
(
  '3 Bedroom Apartment in Legon',
  'Student-friendly 3-bedroom apartment near University of Ghana, Legon. This property is perfect for students or young professionals. Features include modern amenities, good security, and easy access to campus and transport.',
  'Legon, Accra',
  240000,
  3,
  2,
  'Apartment',
  'sale', -- Changed from 'For Sale' to 'sale'
  130,
  2,
  ARRAY['24/7 Security', 'Backup Generator', 'Parking', 'Internet/WiFi'],
  ARRAY['/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600', '/placeholder.svg?height=400&width=600'],
  'Accential Properties',
  '+233 50 123 4567',
  'active',
  false
);
