-- Insert Locus Estate properties (10 listings, all inactive)
INSERT INTO properties (title, description, property_type, listing_type, price, currency, location, address, region, bedrooms, bathrooms, amenities, status, agent, agent_name, agent_phone, agent_email, agent_company, developer, estate_name, phone, agent_whatsapp, created_at, updated_at)
VALUES
(
  'Locus Place Furnished Apartment',
  'Fully furnished apartment building next to Trasacco Phase. Near Trasacco, quality furnishings, ready to move in. Established 2017 luxury lifestyle developer.',
  'apartment', 'rent', 2000, 'USD',
  'East Legon Hills', 'Next to Trasacco Phase, East Legon Hills', 'Greater Accra',
  2, 2,
  ARRAY['Fully Furnished', '24/7 Security', 'Premium Location'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'Locus Place',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Locus Drive 3-Bedroom Townhouse',
  'Fully furnished 3-bedroom townhouse in East Legon Hills near Ridgeview Gardens. 2-storey, quality furnishings, prime location. 35x100 plot size. Near main road.',
  'townhouse', 'sale', 280000, 'USD',
  'East Legon Hills', 'East Legon Hills near Ridgeview Gardens', 'Greater Accra',
  3, 3,
  ARRAY['Fully Furnished', '24/7 Security', 'Premium Location'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'Locus Drive',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Locus Drive 2 - 4-Bedroom Townhouse',
  'Semi-furnished 4-bedroom townhouse with swimming pool. Modern appliances, spacious living and dining area. 4.5 bathrooms. Staff quarters included.',
  'townhouse', 'sale', 380000, 'USD',
  'East Legon Hills', 'East Legon Hills', 'Greater Accra',
  4, 5,
  ARRAY['Swimming Pool', 'Staff Quarters', '24/7 Security', 'Semi-Furnished', 'Modern Appliances'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'Locus Drive 2',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'East Villa 4-Bedroom with Pool',
  'Luxurious 4-bedroom with swimming pool and master suite. Walk-through closet, double vanity, master suite on 2nd floor. Luxury finishes throughout.',
  'house', 'sale', 450000, 'USD',
  'East Legon Hills', 'East Legon Hills', 'Greater Accra',
  4, 4,
  ARRAY['Swimming Pool', '24/7 Security', 'Premium Location', 'Walk-Through Closet', 'Master Suite'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'East Villa',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Mo''s Residence 3-Bedroom Spintex',
  'Well-crafted semi-detached 3-bedroom with staff quarters and smart refrigerator. High-end kitchen, quality fixtures. Premium Spintex location.',
  'house', 'sale', 250000, 'USD',
  'Spintex', 'Spintex', 'Greater Accra',
  3, 3,
  ARRAY['Staff Quarters', '24/7 Security', 'Semi-Furnished', 'Smart Refrigerator', 'High-End Kitchen'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'Mo''s Residence',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'CASA-AD Aburi Bali-Inspired Home',
  'Exclusive gated community with Bali-inspired homes in cool Aburi landscape. Mountain setting, nature tranquility, luxury living. Cool Aburi climate.',
  'house', 'sale', 350000, 'USD',
  'Aburi', 'Aburi', 'Eastern Region',
  3, 3,
  ARRAY['Gated Community', 'Lush Landscapes', 'Cool Climate', '24/7 Security', 'Bali-Inspired Design'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'CASA-AD',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Lo Colina Aburi Contemporary 3-Bedroom Villa',
  'Contemporary villa in heart of Aburi designed for luxury seekers. Open-plan living, mountain views, elegant furnishings. Views of Accra from hillside.',
  'villa', 'sale', 400000, 'USD',
  'Aburi', 'Heart of Aburi', 'Eastern Region',
  3, 3,
  ARRAY['Lush Green Spaces', 'Open-Plan Living', 'Mountain Views', '24/7 Security', 'Contemporary Design'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'Lo Colina',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Lo Colina Aburi 4.5-Bedroom Villa',
  'Modern villa with 4.5 bedrooms for family living with spectacular Accra views. High-spec finishes, spectacular attention to detail. Convenient to Accra and Aburi.',
  'villa', 'sale', 550000, 'USD',
  'Aburi', 'Heart of Aburi', 'Eastern Region',
  4, 5,
  ARRAY['Lush Green Spaces', 'Open-Plan Living', 'Mountain Views', '24/7 Security', 'High-Spec Finishes'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'Lo Colina',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Locus East Legon Hills 3-Bedroom Villa',
  'Modern villa in center of East Legon Hills. Modern design, high-spec finishes, city center living. 5+ years experience, award-winning designs.',
  'villa', 'sale', 320000, 'USD',
  'East Legon Hills', 'East Legon Hills', 'Greater Accra',
  3, 3,
  ARRAY['24/7 Security', 'Premium Location', 'Modern Design', 'High-Spec Finishes'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'East Legon Hills Villas',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
),
(
  'Locus East Legon Hills 4.5-Bedroom Townhouse',
  'Spacious townhouse for city center living with space. 4.5 bedrooms, spectacular finishes, family living, work-from-home ready. Partnership with Meraki luxury design agency since 2017.',
  'townhouse', 'sale', 420000, 'USD',
  'East Legon Hills', 'East Legon Hills', 'Greater Accra',
  4, 5,
  ARRAY['24/7 Security', 'Premium Location', 'Spectacular Finishes', 'Work-From-Home Ready'],
  'inactive', 'Locus Estate', 'Locus Estate',
  '+233 000 000 000', 'info@locusestate.com', 'Locus Estate',
  'Locus Estate', 'East Legon Hills Townhouses',
  '+233 000 000 000', '+233 000 000 000',
  NOW(), NOW()
);
